const { validateCareRules } = require('./validators/careRulesValidator')
const { validateCareService } = require('./validators/careServiceValidator')
const { validateCareDisplayUtils } = require('./validators/careDisplayUtilsValidator')
const { validateCareGuideDisplayUtils } = require('./validators/careGuideDisplayUtilsValidator')
const { validateCareMessagesConfig } = require('./validators/careMessagesConfigValidator')
const { validateCarePanelDisplayUtils } = require('./validators/carePanelDisplayUtilsValidator')
const { validateAchievementDefinitions } = require('./validators/achievementDefinitionsValidator')
const { validateAchievementRules } = require('./validators/achievementRulesValidator')
const { validateAchievementService } = require('./validators/achievementServiceValidator')
const { validateDatabaseArchitecture } = require('./validators/databaseArchitectureValidator')
const { validateDatabaseFacade } = require('./validators/databaseFacadeValidator')
const { validateDefenseConfig } = require('./validators/defenseConfigValidator')
const { validateDiagnosisConfig } = require('./validators/diagnosisConfigValidator')
const { validateDiagnosisDisplayUtils } = require('./validators/diagnosisDisplayUtilsValidator')
const { validateDiagnosisRules } = require('./validators/diagnosisRulesValidator')
const { validateDiagnosisScenarioSelector } = require('./validators/diagnosisScenarioSelectorValidator')
const { validateDiagnosisService } = require('./validators/diagnosisServiceValidator')
const { validateEnvironmentDisplayUtils } = require('./validators/environmentDisplayUtilsValidator')
const { validateIpcHandler } = require('./validators/ipcHandlerValidator')
const { validateMainGameplayContracts } = require('./validators/mainGameplayContractsValidator')
const { validateMinigameService } = require('./validators/minigameServiceValidator')
const { validateNurseryDisplayUtils } = require('./validators/nurseryDisplayUtilsValidator')
const { validatePlantCatalog } = require('./validators/plantCatalogValidator')
const { validatePlantCatalogService } = require('./validators/plantCatalogServiceValidator')
const { validatePlantCollectionService } = require('./validators/plantCollectionServiceValidator')
const { validatePlantPlacementService } = require('./validators/plantPlacementServiceValidator')
const { validatePlantRules } = require('./validators/plantRulesValidator')
const { validatePersistenceCriticalContracts } = require('./validators/persistenceCriticalValidator')
const { validateProgressRules } = require('./validators/progressRulesValidator')
const { validateProfileConfig } = require('./validators/profileConfigValidator')
const { validateProfileDisplayUtils } = require('./validators/profileDisplayUtilsValidator')
const { validateProgressService } = require('./validators/progressServiceValidator')
const { validateQuizDisplayUtils } = require('./validators/quizDisplayUtilsValidator')
const { validateQuizQuestionBank } = require('./validators/quizQuestionBankValidator')
const { validateQuizService } = require('./validators/quizServiceValidator')
const { validateResetService } = require('./validators/resetServiceValidator')
const { validateSimulationRules } = require('./validators/simulationRulesValidator')
const { validateSimulationService } = require('./validators/simulationServiceValidator')
const { validateStatsService } = require('./validators/statsServiceValidator')
const { validateStreakService } = require('./validators/streakServiceValidator')
const { validateWeeklyReviewService } = require('./validators/weeklyReviewServiceValidator')
const { validateWeeklyReviewDisplayUtils } = require('./validators/weeklyReviewDisplayUtilsValidator')
const { validateWeeklyReviewRecommendations } = require('./validators/weeklyReviewRecommendationsValidator')

async function main() {
  validatePlantCatalog()
  validatePlantCatalogService()
  validatePlantCollectionService()
  validatePlantPlacementService()
  validatePlantRules()
  validatePersistenceCriticalContracts()
  validateCareDisplayUtils()
  validateCareGuideDisplayUtils()
  validateCareMessagesConfig()
  validateCarePanelDisplayUtils()
  validateCareRules()
  validateCareService()
  validateProgressRules()
  validateSimulationRules()
  validateSimulationService()
  validateWeeklyReviewService()
  validateWeeklyReviewDisplayUtils()
  validateWeeklyReviewRecommendations()
  validateAchievementDefinitions()
  validateAchievementRules()
  validateAchievementService()
  validateDefenseConfig()
  validateDiagnosisConfig()
  validateDiagnosisDisplayUtils()
  validateDiagnosisRules()
  validateDiagnosisScenarioSelector()
  validateDiagnosisService()
  validateEnvironmentDisplayUtils()
  await validateIpcHandler()
  validateMainGameplayContracts()
  validateMinigameService()
  validateNurseryDisplayUtils()
  validateProfileConfig()
  validateProfileDisplayUtils()
  validateProgressService()
  validateQuizDisplayUtils()
  validateQuizQuestionBank()
  validateQuizService()
  validateResetService()
  validateStatsService()
  validateStreakService()
  validateDatabaseArchitecture()
  validateDatabaseFacade()

  console.log('Validacion ligera de reglas completada correctamente.')
}

main().catch(error => {
  console.error(error)
  process.exitCode = 1
})
